title:              Htet Myet -- In a nutshell
tagline:            htet myet in a nutshell
description:        Enhance 
url:                http://HtetMyet.github.io

author:
  name:             Your Name
  url:              https://twitter.com/htetmyetlynn
  email:            htetmyet@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-architect