title:              Htet Myet
tagline:            in a nutshell
description:        Reconnect with nature
url:                http://HtetMyet.github.io

author:
  name:             Htet Myet Lynn
  url:              https://twitter.com/htetmyetlynn
  email:            htetmyet@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           10
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-architect